version: '2.0'
services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    # depends_on:
    #   - wbms-backend
    networks:
      - armin-net
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - armin-net
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
    networks:
      - armin-net
  wbms-db:
    image: 'bitnami/mariadb'
    restart: always
    ports:
      - 33061:3306
    environment:
      MARIADB_ROOT_USER: wbms_dba
      MARIADB_ROOT_PASSWORD: P@ss3031323334
      MARIADB_USER: wbms_dbu
      MARIADB_PASSWORD: 3031323334
      MARIADB_DATABASE: wbms

      MARIADB_REPLICATION_MODE: master
      MARIADB_REPLICATION_USER: wbms_dbr
      MARIADB_REPLICATION_PASSWORD: 3031323334

      MARIADB_EXTRA_FLAGS: --innodb_strict_mode=0 --innodb_log_file_size=512M --innodb_log_buffer_size=256M

    volumes:
      - mariadb-data-pks04:/bitnami/mariadb
      # - ./database/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
    networks:
      - armin-net
  wbms-phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    networks:
      - armin-net
  wbms-backend:
    image: almyra/wbms_tbe:latest
    depends_on:
      - wbms-db
    restart: always
    ports:
      - 6001:6001
    volumes:
      - ../armin/server/upload:/wbms_be/upload
    networks:
      - armin-net

  wbms-fe:
    image: 'almyra/wbms_fe:latest'
    # depends_on:
    #   - wbms-backend
    restart: always
    # build:
    #     context: ./client
    #     dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - armin-net
      - host
networks:
  armin-net:
    driver: nat
volumes:
  ldap-data:
  ldap-config:
  redis:
  mariadb-data-pks04:
