version: '2.0'
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: wbms.dsn
    cap_add:
      - NET_ADMIN
    cap_drop:
      - MKNOD
    ports:
      - '389:389'
      - '636:636'
    tty: true
    stdin_open: true
    environment:
      LDAP_ORGANISATION: wbms-dsn
      LDAP_DOMAIN: wbms.dsn
      LDAP_BASE_DN: dc=wbms,dc=dsn
      LDAP_TLS_CRT_FILENAME: server.crt
      LDAP_TLS_KEY_FILENAME: server.key
      LDAP_TLS_CA_CRT_FILENAME: wbms.dsn.ca.crt
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config
      LDAP_MAIL_ATTRIBUTE: mail
      # LDAP_READONLY_USER: true
      # LDAP_READONLY_USER_USERNAME: user
      # LDAP_READONLY_USER_PASSWORD: watcher
      LDAP_RFC2307BIS_SCHEMA: true
      LDAP_REMOVE_CONFIG_AFTER_SETUP: true
      # LDAP_SEED_INTERNAL_LDIF_PATH: '/assets/openldap/custom/ldif'
      # LDAP_TLS: false
      LDAP_TLS_DH_PARAM_FILE: /container/service/slapd/assets/certs/dhparam.pem
      # LDAP_TLS_ENFORCE: false
      LDAP_TLS_CIPHER_SUITE: SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC
      LDAP_TLS_VERIFY_CLIENT: never
    command: --copy-service --loglevel debug
    volumes:
      - ldap-data:/container/service/slapd/assets/config/bootstrap/ldif/custom
      # - ldap-config:/etc/ldap/slapd.d
      - ../armin/ldap/config:/etc/ldap/slapd.d
      - ../armin/ldap/certificates:/container/service/slapd/assets/certs
      - ../armin/ldap/database:/var/lib/ldap
      - ../armin/ldif:/assets/openldap/custom/ldif
    networks:
      - armin-net
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap://wbms.dsn
      PHPLDAPADMIN_HTTPS: false
    ports:
      - '18080:80'
    depends_on:
      - openldap
    networks:
      - armin-net
  wbms-db:
    image: 'bitnami/mariadb'
    restart: always
    ports:
      - 33061:3306
    environment:
      MARIADB_ROOT_USER: wbms_dba
      MARIADB_ROOT_PASSWORD: P@ss3031323334
      MARIADB_USER: wbms_dbu
      MARIADB_PASSWORD: 3031323334
      MARIADB_DATABASE: wbms

      MARIADB_REPLICATION_MODE: master
      MARIADB_REPLICATION_USER: wbms_dbr
      MARIADB_REPLICATION_PASSWORD: 3031323334

      MARIADB_EXTRA_FLAGS: --innodb_strict_mode=0 --innodb_log_file_size=512M --innodb_log_buffer_size=256M

    volumes:
      - mariadb-data-pks04:/bitnami/mariadb
      # - ./database/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
    networks:
      - armin-net
  wbms-phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    networks:
      - armin-net
  wbms-backend:
    image: almyra/wbms_tbe:latest
    depends_on:
      - wbms-db
    restart: always
    ports:
      - 6001:6001
    environment:
      WBMS_DB_DOMAIN: 'wbms-db'
      WBMS_DB_PORT: '3306'
      WBMS_DB_USER: 'wbms_dbu'
      WBMS_DB_PASSWORD: '3031323334'
      WBMS_DB_NAME: 'wbms'

      WBMS_SEMAI_API_KEY: 'lg8EzYBtTVJnBuTSjQIJkChoDNlGMpso'
      WBMS_SEMAI_API_URL: 'https://dispatch-api-dev.semaigroup.com/external-channel'
      WBMS_SEMAI_CERT: './cert/pks4.wb.cert.pem'
      WBMS_SEMAI_KEY: './cert/pks4.wb.key.pem'
    volumes:
      - ../armin/server/upload:/wbms_be/upload
    networks:
      - armin-net
  wbms-fe:
    image: 'almyra/wbms_fe:latest'
    depends_on:
      - wbms-backend
    restart: always
    # build:
    #     context: ./client
    #     dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - armin-net
networks:
  armin-net:
    driver: nat
volumes:
  ldap-data:
  ldap-config:
  redis:
  mariadb-data-pks04:
