# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
version: '3.8'
services:
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # command: --interval 43200
    environment:
      - WATCHTOWER_POLL_INTERVAL=43200
    networks:
      - armin-net
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass wbmsapp --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - 6379:6379
    volumes:
      - ../armin/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - armin-net

  # openldap:
  #   image: osixia/openldap:latest
  #   container_name: openldap
  #   hostname: openldap #ldap://0.0.0.0:1389
  #   ports:
  #     - "389:389"
  #     - "636:636"
  #   environment:
  #     - LDAP_ORGANISATION=wbms
  #     - LDAP_DOMAIN=wbms.dsn
  #     - LDAP_ADMIN_USERNAME=admin
  #     - LDAP_ADMIN_PASSWORD=admin_pass
  #     - LDAP_CONFIG_PASSWORD=config_pass
  #     - "LDAP_BASE_DN=dc=wbms,dc=dsn"
  #     - LDAP_TLS=no
  #     - LDAP_READONLY_USER=true
  #     - LDAP_READONLY_USER_USERNAME=user-ro
  #     - LDAP_READONLY_USER_PASSWORD=ro_pass
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - ./data/certificates:/container/service/slapd/assets/certs
  #     - ./data/slapd/database:/var/lib/ldap
  #     - ./data/slapd/config:/etc/ldap/slapd.d
  #   networks:
  #     - armin-net
  # phpldapadmin:
  #   image: osixia/phpldapadmin:latest
  #   container_name: phpldapadmin
  #   environment:
  #     PHPLDAPADMIN_LDAP_HOSTS: "openldap"
  #     PHPLDAPADMIN_HTTPS: "false"
  #   ports:
  #     - "18080:80"
  #   depends_on:
  #     - openldap
  #   networks:
  #     - armin-net
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap #ldap://0.0.0.0:1389
    ports:
      - '389:389'
      - '636:636'
    environment:
      LDAP_ORGANISATION: wbms-dsn
      LDAP_DOMAIN: wbms.dsn
      LDAP_BASE_DN: dc=wbms,dc=dsn
      LDAP_TLS_CRT_FILENAME: server.crt
      LDAP_TLS_KEY_FILENAME: server.key
      LDAP_TLS_CA_CRT_FILENAME: wbms.dsn.ca.crt
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config
      LDAP_READONLY_USER: true
      LDAP_READONLY_USER_USERNAME: user
      LDAP_READONLY_USER_PASSWORD: watcher
      LDAP_RFC2307BIS_SCHEMA: true
      LDAP_REMOVE_CONFIG_AFTER_SETUP: true
      LDAP_SEED_INTERNAL_LDIF_PATH: '/assets/openldap/custom/ldif'
      LDAP_TLS_VERIFY_CLIENT: never
    volumes:
      - ../armin/ldap/slapd/assets/certificates:/container/service/slapd/assets/certs
      - ../armin/ldap/slapd/database:/var/lib/ldaph
      - ../armin/ldap/slapd/config:/etc/ldap/slapd.d
    networks:
      - armin-net
  openldap-ui:
    image: wheelybird/ldap-user-manager:v1.5
    container_name: openldap-ui
    environment:
      LDAP_URI: ldap://openldap
      LDAP_BASE_DN: dc=wbms,dc=dsn
      LDAP_REQUIRE_STARTTLS: false
      LDAP_ADMINS_GROUP: admins
      LDAP_ADMIN_BIND_DN: cn=admin,dc=wbms,dc=dsn
      LDAP_ADMIN_BIND_PWD: admin
      LDAP_USER_OU: Users
      LDAP_GROUP_OU: Groups
      LDAP_IGNORE_CERT_ERRORS: true
      # FORCE_RFC2307BIS: true
      NO_HTTPS: TRUE

      PASSWORD_HASH: SSHA
      SERVER_HOSTNAME: wbms.dsn
    depends_on:
      - openldap
    ports:
      - 18080:80
    networks:
      - armin-net
  wbms-db:
    image: 'bitnami/mariadb'
    restart: always
    ports:
      - 33061:3306

    environment:
      MARIADB_ROOT_USER: wbms_dba
      MARIADB_ROOT_PASSWORD: P@ss3031323334
      MARIADB_USER: wbms_dbu
      MARIADB_PASSWORD: 3031323334
      MARIADB_DATABASE: wbms

      MARIADB_REPLICATION_MODE: master
      MARIADB_REPLICATION_USER: wbms_dbr
      MARIADB_REPLICATION_PASSWORD: 3031323334

      MARIADB_EXTRA_FLAGS: --innodb_strict_mode=0 --innodb_log_file_size=512M --innodb_log_buffer_size=256M

    volumes:
      - ../armin/database/mariadb-data-pks04:/bitnami/mariadb
      # - ./database/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
    networks:
      - armin-net
  wbms-phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    networks:
      - armin-net

  # wbms-backend:
  #   image: almyra/wbms_tbe:latest
  #   depends_on:
  #     - wbms-db
  #   restart: always
  #   ports:
  #     - 6001:6001

  #   environment:
  #     WBMS_APP_PORT: '6001'

  #     WBMS_DB_DOMAIN: 'wbms-db'
  #     WBMS_DB_PORT: '3306'
  #     WBMS_DB_USER: 'wbms_dbu'
  #     WBMS_DB_PASSWORD: '3031323334'
  #     WBMS_DB_NAME: 'wbms'

  #     # 1: PKS, 2: T30, 3: BULKING
  #     WBMS_SITE_TYPE: '1'

  #     WBMS_WB_PORT: '9001'
  #     WBMS_WB_MIN_WEIGHT: 1
  #     WBMS_WB_STABLE_PERIOD: 3000

  #     WBMS_SEMAI_API_KEY: 'lg8EzYBtTVJnBuTSjQIJkChoDNlGMpso'
  #     WBMS_SEMAI_API_URL: 'https://dispatch-api-dev.semaigroup.com/external-channel'
  #     WBMS_SEMAI_CERT: './cert/pks4.wb.cert.pem'
  #     WBMS_SEMAI_KEY: './cert/pks4.wb.key.pem'
  #     UPLOAD_LOCATION: ./upload
  #     MAX_FILE_SIZE: 5000000

  #     LDAP_HOST: 'ldap://ldap.wbms.dsn'
  #     LDAP_DN: 'cn=admin,dc=wbms,dc=dsn'
  #     LDAP_PASSWORD: 'admin'
  #     LDAP_BASE_DN: 'dc=wbms,dc=dsn'
  #     LDAP_SEARCH_FILTER: '(uid={{username}})(email=*@foo.com))'
  #   volumes:
  #     - ../armin/server/upload:/wbms_be/upload
  #   networks:
  #     - armin-net

  # wbms-fo:
  #   image: 'almyra/wbms_fe:latest'
  #   restart: always
  #   ports:
  #     - 8000:3000

  #   networks:
  #     - armin-net

networks:
  armin-net:
    driver: bridge
volumes:
  # ldap-data:
  # ldap-config:
  - ../armin/custom-ldif:/assets/openldap/custom/ldif