WBMS_APP:
  DOMAIN: 'localhost'
  PORT: 6001

WBMS_WB:
  PORT: 9001
  IP: 'localhost'
  MIN_WEIGHT: 1
  STABLE_PERIOD: 3000

WBMS_BONTRIP:
  SUFFIX_BACKDATED_TEMPLATE: '1'
  SUFFIX_BACKDATED_FORM: '1'
  SUFFIX: '1'

WBMS_SITE:
  CODE: 'P04'
  TYPE: 1

SEMAI:
  BACKUPDOMAIN: 'dsn-pks4wb-02'

LDAP_HOST: 'ldap://ldap.wbms.dsn'
LDAP_DN: 'cn:admin,dc:wbms,dc:dsn'
LDAP_PASSWORD: 'admin'
LDAP_BASE_DN: 'dc:wbms,dc:dsn'
LDAP_SEARCH_FILTER: '(uid:{{username}})(email:*@foo.com))'
