WBMS_APP:
  DOMAIN: "localhost"
  PORT: 6001

WBMS_WB:
  PORT: 9001
  IP: 'localhost'
  MIN_WEIGHT: 1
  STABLE_PERIOD: 3000

WBMS_BONTRIP:
  SUFFIX_BACKDATED_TEMPLATE: '1'
  SUFFIX_BACKDATED_FORM: '1'
  SUFFIX: '1'
  
WBMS_SITE:
  CODE: 'P04'
  TYPE: 1

WBMS_SEMAI_API_URL: "https://dispatch.dsngroup.co.id/api/external-channel"

LDAP:
  HOST: 'ldap://ldap.wbms.dsn'
  DN: 'cn:admin,dc:wbms,dc:dsn'
  PASSWORD: 'admin'
  BASE_DN: 'dc:wbms,dc:dsn'
  SEARCH_FILTER: '(uid:{{username}})(email:*@foo.com))'
