

export let Resource = [
    'barcodeData',
    'barcode',
    'citiesData',
    'city',
    'companiesData',
    'company',
    'configsData',
    'config',
    'customersGroupData',
    'customersGroup',
    'customersData',
    'customer',
    'customerTypesData',
    'customerType',
    'driverData',
    'driver',
    'millsData',
    'mill',
    'productGroupsData',
    'productsData',
    'provincesData',
    'province',
    'semai',
    'sitesData',
    'site',
    'storageTanksData',
    'storageTank',
    'transactionsData',
    'transaction',
    'carsData',
    'car',
    'users',
    'weightBridgesData',
  ];