name: Docker Image CI

on:
  push:
    branches: [ "ac" ]
    tags: 
    - 'v*.*.*'
  pull_request:
    branches: [ "ac" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tag/}" >> $GITHUB_ENV
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: GitHub Tag Name example
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"
    - name: Build the tagged Docker image
      uses: docker/setup-buildx-action@v2
      # with:
      #   context: .
      #   file: Dockerfile 
      #   tags: wbms_tbe
    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx build --file Dockerfile --tag wbms_tbe .
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Tag the Docker image
      run: docker tag wbms_tbe wbms_tbe:latest
    - name: Push to DockerHub
      run: docker push wbms_tbe:latest
    - name: Tag the Docker image
      run: docker tag wbms_tbe almyra/wbms_tbe:$(date +'%Y-%m-%d')
    - name: Push the tagged Docker image
      run: docker push almyra/wbms_tbe:$(date +'%Y-%m-%d')

