name: Docker Image CI

on:
  push:
    branches: [ "ac" ]
  pull_request:
    branches: [ "ac" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag wbms_tbe:${{steps.vars.outputs.tag}}
    - name: Tag the Docker image
      run: docker tag wbms_tbe almyra/wbms_tbe:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push almyra/wbms_tbe:${{steps.vars.outputs.tag}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wbms_tbe
    - name: Tag the Docker image
      run: docker tag wbms_tbe almyra/wbms_tbe:latest
    - name: Push to DockerHub
      run: docker push almyra/wbms_tbe:latest
